Repository frozen-valley/frozen-valley, pull requests merged in 2025-01, with the labels that each got.

#35 Introducing Transitions
  bonfire/bonfire.gd
  bonfire/bonfire.tscn
  dialogue/styles/base_style/textbox_with_portrait/custom_textbox_with_portrait_.tscn
  main/level.gd
  main/main.gd
  map/level1/map_level1.gd
  map_levels/level1/map_level1.gd
  map_levels/level1/map_level1.tscn
  map_levels/river_tilemap_atlas.tres
  map_levels/scripts/cross_river_button.gd
  map_levels/scripts/house_area.gd
  map_levels/scripts/item.gd
  map_levels/scripts/partner.gd
  map_levels/scripts/player.gd
  map_levels/scripts/snow.gd
  map_levels/sub_scenes/border.tscn
  map_levels/sub_scenes/house.tscn
  map_levels/sub_scenes/item.tscn
  map_levels/sub_scenes/log_and_stump.tscn
  map_levels/sub_scenes/partner.tscn
  map_levels/sub_scenes/player.tscn
  map_levels/sub_scenes/snow.tscn
  map_levels/sub_scenes/tree.tscn
  stargazing/stargazing.gd
  stargazing/stargazing.tscn
  transitions/bonfire/SceneFire1.png
  transitions/bonfire/SceneFire1.png.import
  transitions/bonfire/SceneFire2.png
  transitions/bonfire/SceneFire2.png.import
  transitions/bonfire/SceneFire3.png
  transitions/bonfire/SceneFire3.png.import
  transitions/bonfire/bonfire_transition.gd
  transitions/bonfire/bonfire_transition.tscn
  transitions/river_cross/SceneBridge.png
  transitions/river_cross/SceneBridge.png.import
  transitions/river_cross/river_cross_transition.gd
  transitions/river_cross/river_cross_transition.tscn
  transitions/stargazing/SceneStargazing.png
  transitions/stargazing/SceneStargazing.png.import
  transitions/stargazing/stargazing_transition.gd
  transitions/stargazing/stargazing_transition.tscn
  transitions/transition.gd
  tree_chop_game/scripts/dead_tree.gd
  tree_chop_game/scripts/dead_tree_game.gd
  tree_chop_game/scripts/quicktime.gd
  tree_chop_game/scripts/quicktime_game.gd
  tree_chop_game/scripts/quicktime_item.gd
  tree_chop_game/scripts/tree_chop_game.gd
  tree_chop_game/tree_chop_game.tscn
Labels: feature

#44 Rework backbones of Bonfire minigame and create Selectable class
  bonfire/bonfire.gd
  bonfire/bonfire.tscn
  bonfire/bonfire_material.gd
  bonfire/bonfire_material.tscn
  bonfire/match.gd
  bonfire/match.tscn
  bonfire/matches.gd
  bonfire/material_button.gd
  bonfire/material_button.tscn
  bonfire/materials/bonfire_material.gd
  bonfire/materials/bonfire_material.tscn
  bonfire/materials/grass.tscn
  bonfire/materials/kindle.tscn
  bonfire/materials/logs.tscn
  bonfire/materials/planks.tscn
  bonfire/materials/twigs.tscn
  bonfire/selectable.gd
  project.godot
Labels: feature, refactor

#50 New journal entries
  UI/Button1.png
  UI/Button1.png.import
  UI/Button1C.png
  UI/Button1C.png.import
  UI/Button1H.png
  UI/Button1H.png.import
  journal/journal.tscn
  journal/pages/journal_page3.tscn
  journal/sprites/JournalPG3.png
  journal/sprites/JournalPG3.png.import
  journal/sprites/JournalPG4.png
  journal/sprites/JournalPG4.png.import
  journal/sprites/JournalPG4opt1.png
  journal/sprites/JournalPG4opt1.png.import
  journal/sprites/JournalPG4opt2.png
  journal/sprites/JournalPG4opt2.png.import
Labels: feature

#57 Fix z-index on map_level2, fix border, make detectors detect only player
  map_levels/level 2/crossing_detector_1.gd
  map_levels/level 2/crossing_detector_2.gd
  map_levels/level 2/map_level2.tscn
  map_levels/sub_scenes/bush1.tscn
  map_levels/sub_scenes/bush2.tscn
  map_levels/sub_scenes/dead_tree.tscn
  map_levels/sub_scenes/hill1.tscn
  map_levels/sub_scenes/hill2.tscn
  rock.tscn
Labels: bugfix
